# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3414c81fc2c63143780f4cee41251651d3074ee5a284417fa13ac072b621295f5020d4521b17fcc035646094a87ca1772fefd7eaa69b060b0266ad92fe03a22d

test:
  secret_key_base: e0c4728bcdab61d04f5b40ad4d7819669e4afa8484511cab8b5377d9ee1389835af6a2e14d3001ba579d4c6dbb7d375fceac971bc60c01a6324f97b7f4a9e540

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
